[Misc] Dragonwell environment variables
alibaba/dragonwell8 pull request #332
Opened 2022-05-30 02:35 UTC by joeyleeeeeee97

Summary: DRAGONWELL_JAVA_OPTIONS(Dragonwell vendor specific java
options), DRAGONWELL_JAVA_TOOL_OPTIONS_JDK_ONLY(ignore JAVA_TOOL_OPTIONS
except for java command)

Test Plan: TestVendorVMOptions.java

Reviewed-by: yuleil, D-D-H

Issue: https://github.com/alibaba/dragonwell8/issues/330

2022-05-30 02:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/dragonwell8?pullRequest=332) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/dragonwell8?pullRequest=332) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/dragonwell8?pullRequest=332) it.</sub>

2022-05-30 10:53 UTC, D-D-H requested changes
A quick comment:
Some extra changes should be made, such as vmError.cpp(it will print the environment vars).

2022-05-31 03:07 UTC, yuleil commented
Can it be implemented like this？

- VM only recognizes `DRAGONWELL_JAVA_OPTIONS`
- and if `DRAGONWELL_JAVA_TOOL_OPTIONS_JDK_ONLY` is recognized in `java.c`, it will be automatically appended to `DRAGONWELL_JAVA_OPTIONS`

2022-06-01 07:36 UTC, joeyleeeeeee97 commented
@D-D-H 
Added in vmErrors.cpp.
Skipped for jvmti.xml,  supporting these Dragonwell options for  JNI_CreateJavaVM seems unnecessary..

![image](https://user-images.githubusercontent.com/30545334/171352312-7a11d6cd-45e5-4f83-9f40-ea9917939c75.png)

2022-06-02 08:16 UTC, D-D-H commented on hotspot/src/share/vm/utilities/vmError.cpp
> +  "JAVA_COMPILER", "PATH", "USERNAME", "DRAGONWELL_JAVA_TOOL_OPTIONS", "DRAGONWELL_JAVA_TOOL_OPTIONS_JDK_ONLY"
missing ',' at the end

2022-06-02 08:20 UTC, D-D-H commented on hotspot/src/share/vm/runtime/arguments.cpp
> +  return parse_options_environment_variable("DRAGONWELL_JAVA_TOOL_OPTIONS", scp_p,
why not use parse_options_environment_variable directly?

2022-06-02 09:18 UTC, joeyleeeeeee97 commented on hotspot/src/share/vm/utilities/vmError.cpp
> +  "JAVA_COMPILER", "PATH", "USERNAME", "DRAGONWELL_JAVA_TOOL_OPTIONS", "DRAGONWELL_JAVA_TOOL_OPTIONS_JDK_ONLY"
done

2022-06-02 09:18 UTC, joeyleeeeeee97 commented on hotspot/src/share/vm/runtime/arguments.cpp
> +  return parse_options_environment_variable("DRAGONWELL_JAVA_TOOL_OPTIONS", scp_p,
![image](https://user-images.githubusercontent.com/30545334/171598243-8d4166d9-c1ea-4e16-a21a-f3145f1fe74a.png)
just like JAVA_TOOL_OPTIONS..

2022-06-02 09:20 UTC, D-D-H commented on hotspot/src/share/vm/utilities/vmError.cpp
> +  "JAVA_COMPILER", "PATH", "USERNAME", "DRAGONWELL_JAVA_TOOL_OPTIONS", "DRAGONWELL_JAVA_TOOL_OPTIONS_JDK_ONLY"
is it really done?

2022-06-02 09:21 UTC, D-D-H commented on hotspot/src/share/vm/runtime/arguments.cpp
> +    if (ignore_unrecognized) {
hmm... If it is an upstream problem, why include this fix in this patch?

2022-06-06 02:19 UTC, joeyleeeeeee97 commented on hotspot/src/share/vm/runtime/arguments.cpp
> +    if (ignore_unrecognized) {
customer requires this function in production, might takes too long to submit to upstream and merge back

2022-06-06 02:22 UTC, joeyleeeeeee97 commented on jdk/src/share/bin/java.c
> +    ifn->SetRunningFromJava(!printVersion&&runFromJava);
arguments are parsed at JNI level, we need to identify whether it is running from `java` and set the state to vm via jni.

2022-06-06 02:40 UTC, joeyleeeeeee97 commented on jdk/src/share/bin/java.c
> +    runFromJava = jargv == NULL;
jargv and jargc is parsed from const_extra_jargs, which controlled by EXTRA_JAVA_ARGS during compilation, for java command EXTRA_JAVA_ARGS is never defined so this is NULL. (for tools this must be defined)

As in dragonwell 11.
    JLI_InitArgProcessing(jargc > 0, const_disable_argfile);

https://github.com/alibaba/dragonwell11/blob/1529c150d3a34b6b01d384147c9d3fe3be1c73ea/src/java.base/share/native/launcher/main.c#L141

2022-06-06 02:41 UTC, joeyleeeeeee97 commented on hotspot/src/share/vm/utilities/vmError.cpp
> +  "JAVA_COMPILER", "PATH", "USERNAME", "DRAGONWELL_JAVA_TOOL_OPTIONS", "DRAGONWELL_JAVA_TOOL_OPTIONS_JDK_ONLY"
yes!..

2022-06-06 10:08 UTC, yuleil approved these changes

2022-06-06 10:51 UTC, D-D-H commented on hotspot/src/share/vm/runtime/arguments.cpp
> +    if (ignore_unrecognized) {
Please add more related comments to the git commit if this change must be included in this patch.

2022-06-06 10:54 UTC, D-D-H commented on hotspot/src/share/vm/runtime/arguments.cpp
> +  return parse_options_environment_variable("DRAGONWELL_JAVA_TOOL_OPTIONS", scp_p,
okay

2022-06-06 10:56 UTC, D-D-H commented on hotspot/src/share/vm/runtime/arguments.cpp
> +    } else if (match_option(option, "-XX:+IgnoreUnrecognizedVMOptions", &tail)) {
Please add more related comments to the git commit if this change must be included in this patch.

2022-06-06 10:57 UTC, D-D-H commented
I still don't think it's a good idea to include IgnoreUnrecognizedVMOptions fix change in this patch.
@yuleil What do you think?

2022-06-06 11:52 UTC, D-D-H approved these changes

2022-06-07 02:46 UTC, merged